services: 
  web:
    build: . 
    command: sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:${APP_PORT}" 
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
    image: social_networking_app 
    expose: 
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: "always"
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGPORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}

    restart: "on-failure"
    
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data: