# Generated by Django 5.0.7 on 2024-09-27 02:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0003_alter_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="cooldown_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BlockDetail",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_app.userprofile",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_details",
                        to="social_app.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
