# Generated by Django 5.0.7 on 2024-09-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0004_friendrequest_cooldown_time_blockdetail"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blockdetail",
            unique_together={("blocker", "blocked")},
        ),
    ]
